# Generated by Django 6.0.2 on 2026-02-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantattribute',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='productvariantattribute',
            name='attribute',
        ),
        migrations.AddField(
            model_name='product',
            name='variant_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product'),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='ProductVariantAttribute',
        ),
    ]
