# Generated by Django 6.0.2 on 2026-03-09 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0009_product_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('none', 'none'), ('canceled', 'canceled'), ('paid', 'paid'), ('done', 'done')], default='none', max_length=15)),
                ('pay_at', models.DateTimeField(default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('ref_id', models.CharField(default='', max_length=1023, null=True)),
                ('trx_id', models.CharField(default='', max_length=1023, null=True)),
                ('amount', models.FloatField(default=0, null=True)),
                ('status', models.CharField(choices=[('none', 'none'), ('init', 'init'), ('processing', 'processing'), ('rejected', 'rejected'), ('completed', 'completed')], default='none')),
                ('status_code', models.IntegerField(default=-1)),
                ('expires_at', models.DateTimeField(default=None)),
                ('pay_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(max_length=127)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='orders.order')),
            ],
        ),
    ]
